spring:
  application:
    name: assignment

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        type:
          preferred_enum_jdbc_type: VARCHAR
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

logging:
  level:
    root: info
    com.realteeth.assignment: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Mock Worker 설정
mock-worker:
  base-url: https://dev.realteeth.ai/mock
  api-key: mock_b64d77a3625b4dd099387479769f557e